### ISSUE TITLE
Distracting bar along the top with new Proton UI (FF 89.0)

### ISSUE THREAD

**Issue by catwithbanana** [ChristosBouronikos/Nord-Polar-Night-Theme#1]
The Firefox UI updated significantly with the release of 89.0 today. While using the Nord Polar Night Theme there is an unnecessary and distracting line that runs the width of the browser just above the address bar and buttons, below the tabs.

Also -- the look of the tabs got changed. While I don't care for the new tab look, I think they would look better within Nord Polar if the active tab was highlighted with a tint (like the default dark theme) rather than an outline (like current Nord Polar).

Thank you!

**Comment by ChristosBouronikos** [comment]
Hey, thanks for reaching out to me. 

Although I'm on the beta channel and on version 89 for a while I don't see the highlighted bar across the top of the whole browser.

What operating system are you using?
Could you provide a few screenshots so that it's clearer what the problem is? 

About highlighting the current tab, I'll gladly look into changing the code to implement that as soon as possible. 

I'll be sure to update you with a new comment if I release a new version of the theme.

**Comment by catwithbanana** [comment]
I'm on Windows 10. As far as I know I'm not using any UI extensions or add-ons other than Dark Reader, which shouldn't affect the UI chrome.

Here is an image where the line is visible:
https://i.imgur.com/eKCDNsz.png

**Comment by ChristosBouronikos** [comment]
Are you referring to the grey-ish line between the URL bar and the tabs or the blue-ish tint around the active tab?

I'm only just noticing the horizontal bar. Will fix this as soon as possible. 

Thanks for bringing it to my attention!

**Comment by catwithbanana** [comment]
Apologies for being unclear -- I was referring to the gray line. I don't like the blue outline either (I would prefer a whole tab tint like the official dark theme), but I understand that's more of a personal preference thing, whereas the gray line seems like an error.

I appreciate your quick response, and thank you for your hard work on this theme!

**Comment by ChristosBouronikos** [comment]
Will look into how to remove the gray bar. And update you with a comment when a new release is out.

Any suggestions on what the color of the tab should be?

You can support this project by [leaving a review](https://addons.mozilla.org/en-US/firefox/addon/nord-polar-night-theme/) or by [donating](https://www.paypal.me/christosbouronikos).

**Comment by catwithbanana** [comment]
Unfortunately I'm _terrible_ with colors. But in general it could nice as a brightened corresponding color, like the active tab in the official dark theme:
https://i.imgur.com/fxUi211.png

I suppose if it were up to me I'd darken the inactive tabs / bar slightly and have the active bar be the exact same color as the address bar. That would achieve cohesion with only two different shades of color instead of three. Again though, I'm not a designer, so take my suggestions with a grain of salt.

Thanks!

**Comment by ChristosBouronikos** [comment]
Thanks so much for the suggestion. I will take it into account when I look into this.

**Comment by ChristosBouronikos** [comment]
@catwithbanana By the way you're incredibly generous, thank you so much!!!

**Comment by ChristosBouronikos** [comment]
@catwithbanana I think I fixed the issue with the gray bar in version 1.18. It should be up in the [add-ons website](https://addons.mozilla.org/en-US/firefox/addon/nord-polar-night-theme/) in the next hours.

I'd appreciate it if you uninstalled and re-installed it from there and reach back with a comment.



You can support this project by [leaving a review](https://addons.mozilla.org/en-US/firefox/addon/nord-polar-night-theme/) or by [donating](https://www.paypal.me/christosbouronikos).

**Comment by catwithbanana** [comment]
Yes, that fixed it. Thank you!

I appreciate you being so responsive and quick to resolve the issue. Have a great week.

**Comment by ChristosBouronikos** [comment]
I'm so glad!
